assets:
  js:
    - bundles/os2displayadmin/assets/libs/jquery.min.js
    - bundles/os2displayadmin/assets/libs/angular.min.js
    - bundles/os2displayadmin/assets/libs/angular-sanitize.min.js
    - bundles/os2displayadmin/assets/libs/angular-animate.min.js
    - bundles/os2displayadmin/assets/libs/angular-route.min.js
    - bundles/os2displayadmin/assets/libs/moment.min.js
    - bundles/os2displayadmin/assets/libs/moment_da_locale.js
    - bundles/os2displayadmin/assets/libs/es5-shim.min.js
    - bundles/os2displayadmin/assets/libs/angular-file-upload.min.js
    - bundles/os2displayadmin/assets/libs/angular-bootstrap-colorpicker.js
    - bundles/os2displayadmin/assets/libs/angular-placeholder.js
    - bundles/os2displayadmin/assets/libs/angular-dnd.js
    - bundles/os2displayadmin/assets/libs/angular-tooltips.min.js
    - bundles/os2displayadmin/assets/libs/datetimepicker.jquery.js
    - bundles/os2displayadmin/assets/libs/locale_da.js
    - bundles/os2displayadmin/assets/libs/stacktrace.min.js
    - bundles/os2displayadmin/assets/libs/md5.min.js
    - bundles/os2displayadmin/assets/libs/paging.js
    - bundles/os2displayadmin/assets/libs/angular-modal-service.min.js
    - bundles/os2displayadmin/assets/libs/angular-translate.min.js
    - bundles/os2displayadmin/assets/libs/angular-translate-loader-static-files.min.js
  css:
    - bundles/os2displayadmin/css/colorpicker.css
    - bundles/os2displayadmin/css/jquery.datetimepicker.css
    - bundles/os2displayadmin/css/angular-tooltips.min.css
    - bundles/os2displayadmin/assets/build/styles.min.css
    - bundles/os2displayadmin/css/styleguide.css
  js_prod_assets:
    - bundles/os2displayadmin/assets/build/assets.min.js
  js_prod:
    - bundles/os2displayadmin/assets/build/os2displayadmin.min.js

bootstrap:
  modules:
    - logModule
    - mainModule
  services:
    - apiService
    - logService
    - userService
    - searchService
    - menuItemService
    - bodyService
    - authHttpResponseInterceptor

modules:
  busModule:
    files:
      - bundles/os2displayadmin/apps/busModule/busModule.js

  logModule:
    files:
      - bundles/os2displayadmin/apps/logModule/services/logService.js
    dependencies:
      - busModule

  mainModule:
    files:
      - bundles/os2displayadmin/apps/mainModule/controller/baseController.js
      - bundles/os2displayadmin/apps/mainModule/controller/baseApiController.js
      - bundles/os2displayadmin/apps/mainModule/services/apiService.js
      - bundles/os2displayadmin/apps/mainModule/services/bodyService.js
      - bundles/os2displayadmin/apps/mainModule/services/menuItemService.js
      - bundles/os2displayadmin/apps/mainModule/services/searchService.js
      - bundles/os2displayadmin/apps/mainModule/services/userService.js
      - bundles/os2displayadmin/apps/mainModule/services/authHttpResponseInterceptor.js

  datetimePicker:
    files:
      - bundles/os2displayadmin/apps/datetimePicker/datetimepicker.js

  styleguideComponentsModule:
    files:
      - bundles/os2displayadmin/apps/styleguideComponentsModule/styleguideComponents.js
      - bundles/os2displayadmin/apps/styleguideComponentsModule/modules/box.js
      - bundles/os2displayadmin/apps/styleguideComponentsModule/modules/buttonIconLink.js
      - bundles/os2displayadmin/apps/styleguideComponentsModule/modules/contentList.js
      - bundles/os2displayadmin/apps/styleguideComponentsModule/modules/contentListItem.js
      - bundles/os2displayadmin/apps/styleguideComponentsModule/modules/panelMenu.js
      - bundles/os2displayadmin/apps/styleguideComponentsModule/modules/popup.js

  ikShared:
    files:
      - bundles/os2displayadmin/apps/ikShared/services/mediaFactory.js
      - bundles/os2displayadmin/apps/ikShared/services/templateFactory.js
      - bundles/os2displayadmin/apps/ikShared/services/slideFactory.js
      - bundles/os2displayadmin/apps/ikShared/services/screenFactory.js
      - bundles/os2displayadmin/apps/ikShared/services/channelFactory.js
      - bundles/os2displayadmin/apps/ikShared/services/sharedSearchFactory.js
      - bundles/os2displayadmin/apps/ikShared/services/sharedChannelFactory.js
      - bundles/os2displayadmin/apps/ikShared/services/kobaFactory.js
      - bundles/os2displayadmin/apps/ikShared/controller/baseSearchController.js
      - bundles/os2displayadmin/apps/ikShared/controller/baseEntityController.js
      - bundles/os2displayadmin/apps/ikShared/elements/actionsMenu/actionsMenuDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/actionReloadScreen/actionReloadScreenDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/sharedChannel/sharedChannelDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/sharedChannelOverview/sharedChannelOverview.js
      - bundles/os2displayadmin/apps/ikShared/elements/channel/channelDirectives.js
      - bundles/os2displayadmin/apps/ikShared/elements/channelOverview/channelOverviewDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/pager/pagerDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/delete/deleteDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/channelShare/channelShareDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/checklist/checklistDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/itkHeader/itkHeader.js
      - bundles/os2displayadmin/apps/ikShared/elements/screen/screenDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/slideOverview/slideOverviewDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/slide/slideDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/slide/slideEditableDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/slide/sharedSlideDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/screenOverview/screenOverviewDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/mediaOverview/mediaOverviewDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/mediaUpload/mediaUploadDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/thumb/thumbDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/autoGrow/autoGrowDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/includeReplace/includeReplaceDirective.js
      - bundles/os2displayadmin/apps/ikShared/elements/controlPanel/control-panel.js
      - bundles/os2displayadmin/apps/ikShared/elements/ngModal/ng-modal.js
      - bundles/os2displayadmin/apps/ikShared/elements/disabledList/disabledList.js
      - bundles/os2displayadmin/apps/ikShared/widgets/screenTemplatePickerWidget/screenTemplatePickerWidget.js
      - bundles/os2displayadmin/apps/ikShared/widgets/textWidget/textWidget.js
      - bundles/os2displayadmin/apps/ikShared/widgets/textAreaWidget/textAreaWidget.js
      - bundles/os2displayadmin/apps/ikShared/widgets/numberWidget/numberWidget.js
      - bundles/os2displayadmin/apps/ikShared/widgets/channelPickerWidget/channelPickerWidget.js
      - bundles/os2displayadmin/apps/ikShared/widgets/sharedChannelPickerWidget/sharedChannelPickerWidget.js
      - bundles/os2displayadmin/apps/ikShared/widgets/channelRemoverWidget/channelRemoverWidget.js
      - bundles/os2displayadmin/apps/ikShared/widgets/regionPreviewWidget/regionPreviewWidget.js

apps:
  menuApp:
    container: false
    class: menu-app
    files:
      - bundles/os2displayadmin/apps/menuApp/directive/mainMenuDirective.js
      - bundles/os2displayadmin/apps/menuApp/directive/hamburgerMenuDirective.js
      - bundles/os2displayadmin/apps/menuApp/directive/subMenuDirective.js
    template: /bundles/os2displayadmin/apps/menuApp/menu.html
    dependencies:
      - busModule
      - mainModule

  messageApp:
    container: true
    files:
      - bundles/os2displayadmin/apps/messageApp/directive/messagesDirective.js
    template: bundles/os2displayadmin/apps/messageApp/message.html
    dependencies:
      - busModule
      - mainModule

  ikApp:
    container: true
    class: has-legacy-form-styling
    files:
      - bundles/os2displayadmin/apps/ikApp/ikApp.js
      - bundles/os2displayadmin/apps/ikApp/routing.js
      - bundles/os2displayadmin/apps/ikApp/shared/filters/activeEvents.js
      - bundles/os2displayadmin/apps/ikApp/pages/screen/screen.js
      - bundles/os2displayadmin/apps/ikApp/pages/sharedChannel/sharedChannelController.js
      - bundles/os2displayadmin/apps/ikApp/pages/adminSharing/adminSharingController.js
      - bundles/os2displayadmin/apps/ikApp/pages/adminTemplates/adminTemplatesController.js
      - bundles/os2displayadmin/apps/ikApp/pages/channel/channelController.js
      - bundles/os2displayadmin/apps/ikApp/pages/channelOverview/channelOverviewController.js
      - bundles/os2displayadmin/apps/ikApp/pages/mediaOverview/mediaOverviewController.js
      - bundles/os2displayadmin/apps/ikApp/pages/mediaEdit/mediaEditController.js
      - bundles/os2displayadmin/apps/ikApp/pages/slideOverview/slideOverviewController.js
      - bundles/os2displayadmin/apps/ikApp/pages/slide/slideController.js
      - bundles/os2displayadmin/apps/ikApp/pages/slide/slideEditController.js
      - bundles/os2displayadmin/apps/ikApp/shared/components/date/dateComponent.js
      - bundles/os2displayadmin/apps/ikApp/shared/components/digital-clock/digitalClockComponent.js
    dependencies:
      - busModule
      - mainModule
      - ngRoute
      - ngAnimate
      - ngSanitize
      - angularFileUpload
      - colorpicker.module
      - datetimePicker
      - ngLocale
      - taiPlaceholder
      - ngModal
      - angular-dnd
      - pascalprecht.translate
      - 720kb.tooltips
      - itkControlPanel
      - itkScreenTemplatePickerWidget
      - itkTextWidget
      - itkTextAreaWidget
      - itkNumberWidget
      - itkChannelPickerWidget
      - itkSharedChannelPickerWidget
      - itkChannelRemoverWidget
      - itkRegionPreviewWidget
      - itkDateComponent
      - itkDigitalClockComponent
      - toolsModule
      - ikShared

  timelineApp:
    container: true
    files:
      - bundles/os2displayadmin/apps/timelineApp/assets/vis/dist/vis.min.js
      - bundles/os2displayadmin/apps/timelineApp/timelineApp.js
      - bundles/os2displayadmin/apps/timelineApp/directive/timelineDirective.js
      - bundles/os2displayadmin/apps/timelineApp/services/timelineService.js
      - bundles/os2displayadmin/apps/timelineApp/timelineBaseController.js
      - bundles/os2displayadmin/apps/timelineApp/timelineScreenController.js
      - bundles/os2displayadmin/apps/timelineApp/timelineChannelController.js
    dependencies:
      - busModule
      - mainModule
      - ngRoute
      - bw.paging

  adminApp:
    container: true
    files:
      - bundles/os2displayadmin/apps/adminApp/adminApp.js
      - bundles/os2displayadmin/apps/adminApp/dashboard/adminDashboardController.js
      - bundles/os2displayadmin/apps/adminApp/group/adminGroupsController.js
      - bundles/os2displayadmin/apps/adminApp/group/adminGroupController.js
      - bundles/os2displayadmin/apps/adminApp/group/popupCreateGroupController.js
      - bundles/os2displayadmin/apps/adminApp/group/popupDeleteGroupController.js
      - bundles/os2displayadmin/apps/adminApp/group/popupAddUserController.js
      - bundles/os2displayadmin/apps/adminApp/user/adminUsersController.js
      - bundles/os2displayadmin/apps/adminApp/user/adminUserController.js
      - bundles/os2displayadmin/apps/adminApp/user/popupCreateUserController.js
      - bundles/os2displayadmin/apps/adminApp/user/popupDeleteUserController.js
      - bundles/os2displayadmin/apps/adminApp/user/popupAddRoleToUserController.js
    dependencies:
      - busModule
      - mainModule
      - styleguideComponentsModule
      - ngRoute
      - angularModalService
      - messageApp
      - pascalprecht.translate

